spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/world
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format-sql: true
